# -*- coding: utf-8 -*-
"""ImportSinceDrive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rx03Ypsg2vWlC7vA5Xb-cVM5JClm9kcA

We use `drive.mount` for mount us Google Drive account in Google Colaboratory.
"""

from google.colab import drive
drive.mount('/content/drive')

"""We can verify that the amount has been made correctly and see a list of its contents with `! ls`."""

! ls /content/drive/MyDrive/Activities/

"""We get the path of the file we want to upload and then we can upload it as we normally do."""

path = '/content/drive/MyDrive/Activities/Activities.xlsx'
import pandas as pd
df = pd.read_excel(path)